# This is a basic workflow to help you get started with Actions

name: hello

#Evento
on:
  workflow_dispatch:
  

# Trabajos
jobs:
  trabajo1:
  # This workflow contains a single job called "build"
  
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      
    # Runs a single command using the runners shell
      - name: Echo Terminal
        run: echo Hello, world!
        
      - name: di la fecha de hoy
        run: date
