# This is a basic workflow to help you get started with Actions

name: 

#Evento
on:
  workflow_dispatch:
  

# Trabajos
jobs:
  trabajo1:
  # This workflow contains a single job called "build"
  
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      
    # Runs a single command using the runners shell
      - name: Echo Terminal
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
